AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  activemq_event_consumer_function

  Sample SAM Template for activemq-consumer-with-sam (Python version)

Globals:
  Function:
    Timeout: 60

Resources:
  LambdaActiveMQConsumerPythonFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: python-activemq-consumer-dynamodb-sam
      CodeUri: activemq_event_consumer_function/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          DYNAMO_DB_TABLE: !Ref ActiveMQDynamoDBTable
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroup
        SubnetIds:
          - !Ref Subnet1
          - !Ref Subnet2
          - !Ref Subnet3
      Events:
        MQEvent:
          Type: MQ
          Properties:
            BatchSize: 100
            MaximumBatchingWindowInSeconds: 5
            Broker: !Ref ActiveMQBrokerArn
            Queues:
              - !Ref ActiveMQQueue
            SourceAccessConfigurations:
              - Type: BASIC_AUTH
                URI: !Ref SecretsManagerSecretForMQ
      Policies:
      - Statement:
        - Sid: ActiveMQPermissionsPolicy
          Effect: Allow
          Action: 
          - mq:DescribeBroker
          - secretsmanager:GetSecretValue
          - ec2:CreateNetworkInterface
          - ec2:DeleteNetworkInterface
          - ec2:DescribeNetworkInterfaces
          - ec2:DescribeSecurityGroups
          - ec2:DescribeSubnets
          - ec2:DescribeVpcs
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource: '*'
      - Statement:
        - Sid: DynamoDBPermissionsPolicy
          Effect: Allow
          Action:
          - dynamodb:GetItem
          - dynamodb:DeleteItem
          - dynamodb:PutItem
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:BatchWriteItem
          - dynamodb:BatchGetItem
          - dynamodb:DescribeTable
          - dynamodb:ConditionCheckItem
          Resource: 
          - !Join ['', ["arn:", "aws:", "dynamodb:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", "table/", !Ref ActiveMQDynamoDBTable]]
          - !Join ['', ["arn:", "aws:", "dynamodb:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", "table/", !Ref ActiveMQDynamoDBTable, "/index/*"]]
      
  ActiveMQDynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: ActiveMQDynamoDBTablePython
      PrimaryKey:
        Name: MessageID
        Type: String

Parameters:  
  ActiveMQBrokerArn:
    Type: String
    Description: Enter the ARN of the ActiveMQBroker
    Default: ACTIVEMQ_BROKER_ARN
  ActiveMQQueue:
    Type: String
    Description: Enter the name of the ActiveMQ queue from which the lambda function will consume messages
    Default: ACTIVEMQ_QUEUE_NAME
  SecretsManagerSecretForMQ:
    Type: String
    Description: Enter the ARN of the secret that has username/password for Active MQ
    Default: ACTIVEMQ_SECRET_ARN
  Subnet1:
    Type: String
    Description: The first of the three private subnets in the ActiveMQ broker's VPC
    Default: ACTIVEMQ_SUBNET_ONE
  Subnet2:
    Type: String
    Description: The second of the three private subnets in the ActiveMQ broker's VPC
    Default: ACTIVEMQ_SUBNET_TWO
  Subnet3:
    Type: String
    Description: The second of the three private subnets in the ActiveMQ broker's VPC
    Default: ACTIVEMQ_SUBNET_THREE
  SecurityGroup:
    Type: String
    Description: The security group associated with this function
    Default: SECURITY_GROUP

Outputs:
  LambdaActiveMQConsumerPythonFunction:
    Description: "Queue Consumer Lambda Function ARN"
    Value: !GetAtt LambdaActiveMQConsumerPythonFunction.Arn
